-- =====================================================================
-- Bilingual Conversation (Live → Conversation tab)
--
-- Two people who speak different languages talk face to face or on a
-- call. Each one's browser transcribes their own speech, and the
-- bilingual-conversation edge function translates every finalized turn
-- into the other person's language. Both see the original and the
-- translation, in one shared transcript.
--
-- This is separate from the audience question flow (translation_questions,
-- 0373/0385): no translation_session, no LiveKit room, no listener page.
--
-- Access model:
--   * The host is a signed-in member. They create the conversation, and
--     the edge function checks auth.uid() = host_user_id on every call.
--   * The guest needs no account. The invite link carries a one-time
--     invite token (stored here only as a sha256 hash). Joining claims the
--     single guest seat and swaps the invite for a per-guest seat token
--     (also hashed), which their browser keeps for reconnects. A forwarded
--     or leaked invite link stops working once the guest has joined, and
--     the host can issue a fresh invite, which removes the current guest.
--   * channel_key is a random secret used as the Realtime topic, so only
--     the two seat holders (who get it from the edge function) can hear
--     presence, live partial text and "new entry" pings.
--
-- Every read and write goes through the edge function with the service
-- role, so neither table gets anon/authenticated policies beyond the
-- host listing their own conversations.
-- =====================================================================

begin;

create table if not exists public.bilingual_conversations (
  id uuid primary key default gen_random_uuid(),
  ministry_id uuid references public.ministry_groups(id) on delete cascade,
  host_user_id uuid not null references auth.users(id) on delete cascade,
  host_name text not null,
  host_language text not null,
  guest_name text,
  guest_language text,
  -- null once the guest has claimed the seat (or the host ended it)
  invite_token_hash text,
  invite_expires_at timestamptz,
  guest_token_hash text,
  guest_joined_at timestamptz,
  channel_key text not null default replace(gen_random_uuid()::text, '-', '') || replace(gen_random_uuid()::text, '-', ''),
  status text not null default 'waiting' check (status in ('waiting', 'active', 'ended')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  ended_at timestamptz
);

create index if not exists idx_bilingual_conversations_host on public.bilingual_conversations(host_user_id, created_at desc);

create table if not exists public.bilingual_conversation_entries (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.bilingual_conversations(id) on delete cascade,
  speaker_role text not null check (speaker_role in ('host', 'guest')),
  speaker_name text not null,
  original_text text not null,
  original_language text not null,
  -- null while the other seat is still empty (filled in when the guest
  -- joins) or when translation failed (translation_failed = true)
  translated_text text,
  translated_language text,
  translation_failed boolean not null default false,
  -- generated by the speaking browser per finalized utterance; a retry of
  -- the same utterance after a dropped response is a no-op, not a duplicate
  client_utterance_id text not null,
  created_at timestamptz not null default now(),
  unique (conversation_id, client_utterance_id)
);

create index if not exists idx_bilingual_conversation_entries_conv on public.bilingual_conversation_entries(conversation_id, created_at);

alter table public.bilingual_conversations enable row level security;
alter table public.bilingual_conversation_entries enable row level security;

-- The host's "Recent conversations" list. Hashes and channel_key are
-- still only ever returned by the edge function's own selects.
drop policy if exists p_bilingual_conversations_host_sel on public.bilingual_conversations;
create policy p_bilingual_conversations_host_sel on public.bilingual_conversations
  for select to authenticated
  using (host_user_id = auth.uid());

revoke all on public.bilingual_conversations from anon;
revoke all on public.bilingual_conversation_entries from anon, authenticated;
revoke all on public.bilingual_conversations from authenticated;
grant select (id, ministry_id, host_name, host_language, guest_name, guest_language, status, created_at, ended_at)
  on public.bilingual_conversations to authenticated;

commit;
